- name: Create Host Definitions
  template: src=hosts_def.j2
            dest=/etc/icinga/objects/myservergroup.cfg
            owner=root
            group=root
            mode=0644
  notify:
   - restart icinga
